In [1]:
import numpy as np

In [2]:
# numpys数组只容纳一种数据类型 分为整数型和浮点型即可
arr1 = np.array([1,2,3.0]) # 内含浮点数即为浮点型数组
print(arr1)

[1. 2. 3.]


In [3]:
#往浮点型数组内插入整数 整数上升为浮点数
#往整数型数组内插入浮点数 浮点数被截断为整数
arr1 = np.array([1,2,4,3])
arr1[0] = 100.9
print(arr1)

[100   2   4   3]


In [4]:
arr1 = np.array([1,2,3])
arr2 = arr1.astype(float) #标准转换类型方法
print(arr2)

[1. 2. 3.]


In [5]:
arr1 = np.array([1,2,3])
print(arr1 / 1) #遇到除法会上升为浮点类型

[1. 2. 3.]


In [6]:
#数组的形状参数 [1 2 3] 形状为 3 / (3,)
#            [[1 3]] 形状为  (1,2)
#            [[[1 2 3]]]形状为 (1,1,3)
arr1 = np.ones((1,1,3)) #传入形状参数
print(arr1)

print(arr1.shape)

[[[1. 1. 1.]]]
(1, 1, 3)


In [7]:
# reshape转换维度 传入-1会自动计算
arr1 = np.arange(10)
arr2 = arr1.reshape(2,-1) #需要能整除
print(arr2)
#降级为一维数组
print(arr2.reshape(-1))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [8]:
#一维 ： 向量    二维 ： 矩阵
import numpy as np

In [9]:
#创建递增数组 arange  array_range
arr1 = np.arange(0,10,2)
print(arr1)
print(arr1[[0,1]])

[0 2 4 6 8]
[0 2]


In [10]:
#创建同值数组
arr1 = np.zeros((1,2,3))
print(arr1)


[[[0. 0. 0.]
  [0. 0. 0.]]]


In [11]:
#创建随机数组 np.random
arr1 = np.random.random(5)  #0-1分布
print(arr1)
arr2 = np.random.randint(10,100,(1,5)) #范围[10,100) 整数型随机数组
print(arr2)
arr3 = np.random.normal(0,1,(2,3)) #服从正态分布 输入（均值，标准差，形状）
print(arr3)

[0.84431472 0.5242247  0.4799092  0.00930622 0.17399778]
[[74 94 38 84 55]]
[[ 0.2601471  -0.52167551 -0.72805143]
 [-0.290256   -1.79778922 -0.23233651]]


In [12]:
#访问数组元素
arr = np.array([[1,2,3] ,[4,5,6]])
print(arr[1,1])

5


In [13]:
#花式索引
arr[[1,1],[1,2]] = 100
print(arr)

[[  1   2   3]
 [  4 100 100]]


In [14]:
#矩阵切片
arr2 = np.arange(0,20).reshape(4,5)
arr3 = arr2 [0 : 3,1 : -1]
print(arr3)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [15]:
#numpy数组切片仅是视图 不会创建新变量 
#修改切片 原数组同步改变

In [16]:
arr = [1,2,3]
copy_arr = arr.copy()
copy_arr[0] = 100;
print(arr,copy_arr)


[1, 2, 3] [100, 2, 3]


In [17]:
#numpy数组之间赋值也不会创建新变量 仅是原数组的一个绑定

In [18]:
#数组的变形
#数组的转置方法.T 仅对矩阵有效 因此遇到向量先转化为矩阵
arr = np.arange(1,4).reshape(1,-1)
arr1 = arr.T
print(arr,arr1)

[[1 2 3]] [[1]
 [2]
 [3]]


In [19]:
#翻转 np.flipud() np.fliplr  向量只能上下翻转（实际数学中向量是竖着排）
arr1 = np.arange(10)
arr2 = np.flipud(arr1)
print(arr2)

[9 8 7 6 5 4 3 2 1 0]


In [20]:
#数组的拼接
arr1 = np.array( [[1,2,3] , [4,5,6]] )
arr2 = np.array( [[101,102,103] , [104,105,106] ])
arr3 = np.concatenate([arr1,arr2] ,axis = 1) #axis默认=0（增加行的方向)
print(arr3)

[[  1   2   3 101 102 103]
 [  4   5   6 104 105 106]]


In [21]:
#数组的分裂
arr = np.arange(10)
arr1,arr2,arr3 = np.split(arr,[1,5])
print(arr1,arr2,arr3)

[0] [1 2 3 4] [5 6 7 8 9]


In [22]:
arr = np.arange(30).reshape(5,6)
print(arr)
arr1,arr2,arr3,arr4 = np.split(arr,[1,2,4],axis = 1)
print(arr1,arr2,arr3,arr4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[ 0]
 [ 6]
 [12]
 [18]
 [24]] [[ 1]
 [ 7]
 [13]
 [19]
 [25]] [[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]
 [26 27]] [[ 4  5]
 [10 11]
 [16 17]
 [22 23]
 [28 29]]


In [23]:
#数组的运算
#乘法，除法 对应元素直接乘除
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(arr1 * arr2)

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [24]:
#广播（不同形状数组之间运算的情况）
#向量与矩阵 ： 向量升级为行矩阵
#某矩阵是行矩阵或列矩阵 广播以适配另一个矩阵的形状


In [25]:
#数组的函数
arr1 = np.arange(5)
arr2 = np.arange(15).reshape(5,3)
print(arr1,'\n')
print(arr2,'\n')
print(np.dot(arr1,arr2))
#np.abs np.sin np.cos ... 指数函数：np.exp() 对数：np.log() 默认ln

[0 1 2 3 4] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

[ 90 100 110]


In [26]:
#np.max(,axis) np.sum(,axis) np.prod(,axis)求积   np.mean()均值 np.std标准差 
#若存在缺失值可以加nan忽略缺失值e.g. np.nanmax()

In [27]:
#布尔型数组
#python: and or not
#numpy :  &  |   ~
#np.num() 统计true的个数

#np.any() 有一个true返回true
#np.all() 全为true 返回true

#np.where( boolean array) 返回 （满足要求的索引数组，数据类型） 的元组

In [28]:
#数组到张量 基础语法基本一致
#np 对应 torch
#array对应tensor
#n维数组对应 n阶张量