In [1]:
import torch

In [7]:
x = torch.arange(12)
x
x.shape


torch.Size([12])

In [8]:
#元素个数
x.numel()


12

In [10]:
X = x.reshape(-1, 1)
X

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]])

In [12]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
#提供python列表给张量赋值
y = torch.tensor([[1,2,3],[4,5,6]])
y.shape

torch.Size([2, 3])

In [17]:
x1 = torch.arange(6,dtype = torch.float32).reshape(2,3)
x2 = torch.arange(6,12,dtype = torch.float32).reshape(2,3)
x3 = torch.cat((x1,x2),dim = 0) #dim从最外层[]开始算 dim决定合并第几个维度
x3,torch.cat((x1,x2),dim = 1)

(tensor([[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  6.,  7.,  8.],
         [ 3.,  4.,  5.,  9., 10., 11.]]))

In [18]:
x1  == x2

tensor([[False, False, False],
        [False, False, False]])

In [19]:
x1.sum()

tensor(15.)

In [22]:
#广播机制
a = torch.tensor([[0,1]])
b = torch.tensor( [[1],[2]])
a + b

tensor([[1, 2],
        [2, 3]])

In [26]:
#运行某些操作会导致分配内存给新结果  e.g.赋值
#解决：
z = torch.zeros_like(x1)
before = id(z)
z[:] = x1 + x2
id(z) == before 

#X[:] = X + Y or X += Y 

False

In [29]:
a = torch.tensor([5.2])
a,a.item(),int(a)

(tensor([5.2000]), 5.199999809265137, 5)